# Created by Matthew Valancy
# Copyright 2026 Valpatel Software LLC
# Licensed under AGPL-3.0 — see LICENSE for details.
"""ObjectiveTracker -- evaluates bonus objective completion during gameplay.

Subscribes to EventBus events to track progress toward bonus objectives
generated by the MissionDirector.  Publishes ``bonus_objective_completed``
events when objectives are first met.

Usage:
    tracker = ObjectiveTracker(objectives, game_mode_type, event_bus)
    # Called from engine tick loop:
    tracker.tick(dt)
    # Called at game end:
    tracker.check_all(elapsed_time=300.0, infrastructure_health=950.0)
    # Query state:
    status = tracker.get_status()
"""

from __future__ import annotations

import queue
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from engine.comms.event_bus import EventBus


class ObjectiveTracker:
    """Tracks and evaluates bonus objective completion.

    Each objective is identified by name and evaluated based on a combination
    of real-time event tracking (via EventBus subscription) and end-of-game
    threshold checks.

    Objective evaluation rules:
    - "No casualties" / "Flawless AA": fail if any friendly eliminated
    - "Speed run": complete if elapsed_time < 300s at game end
    - "Zero Collateral": fail if any civilian_harmed event
    - "Quick Containment": fail if any critical density cell
    - "All Instigators Identified": complete if identified == total spawned
    - "Perfect Defense": complete if infrastructure_health > 800 at game end
    - "No Bombers Through": fail if any bomber_detonation event
    - "EMP Master": complete immediately when a single EMP disables 10+ drones
    - "Ace Pilot": complete if any single friendly unit scores 15+ eliminations
    - "Master De-escalator": complete if 20+ de-escalation events
    """

    def __init__(
        self,
        objectives: list[dict] | None,
        game_mode_type: str,
        event_bus: EventBus,
    ) -> None:
        self._event_bus = event_bus
        self._game_mode_type = game_mode_type

        # Normalize objectives list
        if objectives is None:
            objectives = []
        self._objectives: list[dict] = [
            {
                "name": o.get("name", ""),
                "description": o.get("description", ""),
                "reward": o.get("reward", 0),
                "completed": False,
                "failed": False,
            }
            for o in objectives
        ]

        # Build name -> objective index for fast lookup
        self._by_name: dict[str, dict] = {o["name"]: o for o in self._objectives}

        # Subscribe to event bus for real-time tracking.
        # Handles both the real EventBus.subscribe() (no args) and test mocks
        # that may require a topic argument.
        try:
            self._sub: queue.Queue = event_bus.subscribe()
        except TypeError:
            # Fallback for SimpleEventBus-style mocks that require a topic
            self._sub = queue.Queue()

        # Tracking state
        self._friendly_eliminated: bool = False
        self._civilian_harm_count: int = 0
        self._critical_density_seen: bool = False
        self._bomber_detonation_count: int = 0
        self._instigators_identified: int = 0
        self._instigator_total: int = 0
        self._de_escalation_count: int = 0
        self._emp_max_disabled: int = 0
        self._kills_per_unit: dict[str, int] = {}  # interceptor_id -> kill count

    def set_instigator_count(self, total: int) -> None:
        """Set the total number of instigators spawned (for tracking)."""
        self._instigator_total = total

    def tick(self, dt: float) -> None:
        """Process buffered EventBus events.  Called from engine tick loop."""
        for _ in range(200):  # drain up to 200 events per tick
            try:
                msg = self._sub.get_nowait()
            except queue.Empty:
                break
            self._process_event(msg)

    def _process_event(self, msg: dict) -> None:
        """Handle a single event from the EventBus."""
        event_type = msg.get("type", "")
        data = msg.get("data", {})
        if data is None:
            data = {}

        if event_type == "target_eliminated":
            alliance = data.get("target_alliance", "")
            if alliance == "friendly":
                self._friendly_eliminated = True

            # Track per-unit kills for Ace Pilot
            interceptor_id = data.get("interceptor_id")
            interceptor_alliance = data.get("interceptor_alliance", "")
            target_alliance = data.get("target_alliance", "")
            if (interceptor_id
                    and interceptor_alliance == "friendly"
                    and target_alliance == "hostile"):
                self._kills_per_unit[interceptor_id] = (
                    self._kills_per_unit.get(interceptor_id, 0) + 1
                )

        elif event_type == "civilian_harmed":
            self._civilian_harm_count += 1

        elif event_type == "crowd_density":
            if data.get("critical_count", 0) > 0 or data.get("max_density") == "critical":
                self._critical_density_seen = True

        elif event_type == "instigator_identified":
            self._instigators_identified += 1

        elif event_type == "de_escalation":
            self._de_escalation_count += 1

        elif event_type == "bomber_detonation":
            self._bomber_detonation_count += 1

        elif event_type == "emp_activated":
            disabled = data.get("drones_disabled", 0)
            if disabled > self._emp_max_disabled:
                self._emp_max_disabled = disabled
            # Immediate completion check for EMP Master
            if disabled >= 10:
                self._complete_objective("EMP Master")

    def check_all(
        self,
        elapsed_time: float = 0.0,
        infrastructure_health: float = 0.0,
    ) -> None:
        """Evaluate all objectives at game end.

        Time-based and threshold objectives are checked here.
        Event-driven objectives (like EMP Master) may already be completed
        from tick() processing.

        Args:
            elapsed_time: Total game time in seconds.
            infrastructure_health: Final infrastructure health value.
        """
        for obj in self._objectives:
            if obj["completed"]:
                continue  # Already completed

            name = obj["name"]

            if name == "No casualties" or name == "Flawless AA":
                if not self._friendly_eliminated:
                    self._complete_objective(name)

            elif name == "Speed run":
                if elapsed_time < 300.0:
                    self._complete_objective(name)

            elif name == "Zero Collateral":
                if self._civilian_harm_count == 0:
                    self._complete_objective(name)

            elif name == "Quick Containment":
                if not self._critical_density_seen:
                    self._complete_objective(name)

            elif name == "All Instigators Identified":
                if (self._instigator_total > 0
                        and self._instigators_identified >= self._instigator_total):
                    self._complete_objective(name)

            elif name == "Perfect Defense":
                if infrastructure_health > 800.0:
                    self._complete_objective(name)

            elif name == "No Bombers Through":
                if self._bomber_detonation_count == 0:
                    self._complete_objective(name)

            elif name == "EMP Master":
                if self._emp_max_disabled >= 10:
                    self._complete_objective(name)

            elif name == "Ace Pilot":
                max_kills = max(self._kills_per_unit.values(), default=0)
                if max_kills >= 15:
                    self._complete_objective(name)

            elif name == "Master De-escalator":
                if self._de_escalation_count >= 20:
                    self._complete_objective(name)

    def _complete_objective(self, name: str) -> None:
        """Mark an objective as completed and publish the event."""
        obj = self._by_name.get(name)
        if obj is None or obj["completed"]:
            return
        obj["completed"] = True
        self._event_bus.publish("bonus_objective_completed", {
            "name": name,
            "reward": obj["reward"],
        })

    def get_status(self) -> list[dict]:
        """Return current status of all objectives.

        Returns:
            List of dicts: [{"name": str, "completed": bool, "reward": int}, ...]
        """
        return [
            {
                "name": o["name"],
                "completed": o["completed"],
                "reward": o["reward"],
            }
            for o in self._objectives
        ]

    def reset(self) -> None:
        """Reset all tracking state. Called on game reset."""
        for o in self._objectives:
            o["completed"] = False
            o["failed"] = False
        self._friendly_eliminated = False
        self._civilian_harm_count = 0
        self._critical_density_seen = False
        self._bomber_detonation_count = 0
        self._instigators_identified = 0
        self._instigator_total = 0
        self._de_escalation_count = 0
        self._emp_max_disabled = 0
        self._kills_per_unit.clear()
        # Drain stale events
        while True:
            try:
                self._sub.get_nowait()
            except queue.Empty:
                break
